exports.TOKEN = 'NjY2MTAzMzkxNDY2MDI5MDg3.XhvTRA.gaxEMLOmrMMpCAAEiK8LDCrn9H0';

exports.PREFIX = '-';

exports.STATUS = 'BUILD WITH DARKNESS';
// SO OK HERE WE PUT OUR TOKEN , PREFIX, STATUS SO LETS CHECK THE BOT